# Site settings
title: Justin Chiou
tag_text: Hey there!
description: Welcome to my site! Here, you see all the projects I've contributed to.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
